# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chamal-code.pathdoc
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-09-16
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/chamal-code/pathdoc/releases/download/v0.1.0/pathdoc-0.1.0-x86_64-pc-windows-msvc.zip
    InstallerSha256: A46B703AD02E6BCB88865516AF6533CA1D7E1F074FC2C41AEDC6D4F9EBEFC46B
    NestedInstallerFiles:
      - RelativeFilePath: pathdoc-0.1.0-x86_64-pc-windows-msvc\pathdoc.exe
        PortableCommandAlias: pathdoc
ManifestType: installer
ManifestVersion: 1.12.0
